= ConvertFrom-ScriptSettings
:author: Oscar Guillermo Castro Jr.
:revdate: September 26, 2019
:source-highlighter: rouge
:rouge-theme: gruvbox

== Summary
AppSettings but for PowerShell!

Converts a `scriptsettings` file to an IConfiguration object for use in PowerShell.
ScriptSettings is based off C#'s `AppSettings.json`.
The codebase uses similar code that ASP .NET Core projects use.
See the example below for clarity on how to access values in the scriptsettings file.

== Usage

ScriptSettings depends on the `POWERSHELLCORE_ENVIRONMENT` variable to load the correct file.
At most, ScriptSettings will load 3 JSON files; the default scriptsettings.json, scriptsettings.<environment>.json, and a specified JSON file.
The specified file has the highest precedence, followed by the environment variable set file, and finally the default file.

The cmdlet wll search the current working directory for a scriptsettings.json file. If the environmental variable is set, the cmdlet will attempt to load a scriptsettings.<environment>.json file.
Both of these files are optional and will not cause the cmdlet to throw an exception.

NOTE:  If a JSON file is specified, the file must be present!

.Precedence (in descending order)
    . Specified JSON file
    . scriptsettings.<environment>.json
    . scriptsettings.json

[source, powershell]
.ScriptSettings Usage
----
<#
    scriptsettings.json
    {
        "USA": 1776
        "Nuget": {
            "Source": "example.com/feed"
        },
        "Cool Movies": [
            "Harry Potter Series",
            "Stuber",
            "IT Chapter Two"
        ],
        "Cool API Key": "cool-api-key",
        "Quotes": {
            "Caesar": "The fault, dear Brutus, is not in our stars, but in ourselves."
        }
    }

    $env:POWERSHELLCORE_ENVIRONMENT = Development
    scriptsettings.Development.json
    {
        "Cool API Key": "super-cool-api-key",
        "Quotes": {
            "Caesar": "Beware the ides of March."
        }
    }

    scriptsettings.Foo.json (Specified file, could be named anything but must have JSON extension)
    {
        Quotes: {
            "Caesar": "Et tu, Brute?"
        }
    }

#>
$config = ConvertFrom-ScriptSettings -ScriptSettingsFile "./scriptsettings.Foo.json"

$usaYear = $config["USA"] # typical access (value: 1776)
$feed = $config["Nuget:Source"] # Nested key-value pair (value: 'example.com/feed')
$itMovie = $config["Cool Movies:2"] # Access an array (value: 'IT Chapter Two')
$apiKey = $config["Cool API Key"] # Environment variable based file has greater precedence than the default (value: "super-cool-api-key")
$quote = $config["Quotes:Caesar"] # Specified file has highest precedence (value: "Et tu , Brute?")
----

== Project Organization
The project is organized into two primary folders, 'tests' and 'source'.
After the `build.ps1` and `publish.ps1` scripts are ran, other folders are made.

.Folders
    . Builds - contains builds
    . source - contains source code
    . tests - contains test code

=== Build.ps1
Builds the project into the 'builds' folder.
Requires that the scriptsettings file include the Module version and the Nuget source for publishing to Github Package Registry.

=== Publish.ps1
As of September 2019, Publish-Module does not include major support for publishing modules to the Github Package Registry.
In that vein, I've setup a hack-ish script to publish to the registry.
The solution involves publishing to a local repository and pushing that nupkg.

=== Test.ps1
Invokes pester tests in the 'tests' folder.